### ISSUE TITLE
Gentoo ebuild packaging

### ISSUE THREAD

**Issue by 0xC0ncord** [Hexavalent-Browser/Hexavalent#121]
I'm interested in developing an ebuild for Hexavalent at some point. Binary builds are easy as the ebuild can just install the official build.

Source ebuilds are also desireable, but we'd need to figure out the branding issues. Namely, are custom builds allowed to have the Hexavalent name and logo so long as they are not distributed (a la Firefox builds)? If not, what should the package be called?

**Comment by flawedworld** [comment]
We can do an official ebuild of the binary.

We can do an unbranded generically named chromium-browser-hardened setup for users who want to build from source and want the hardening, they will just get the chromium branding cosmetically.

**Comment by 0xC0ncord** [comment]
> We can do an unbranded generically named chromium-browser-hardened setup for users who want to build from source and want the hardening, they will just get the chromium branding cosmetically.

I think this would work. I am only worried about potential confusion because the source ebuild may lack any references to the Hexavalent name and users may not be aware it is essentially Hexavalent but without any of the official branding.

Using Firefox as an example again, in Gentoo the Firefox ebuild has the `bindist` USE flag, which disables the official Firefox branding but with the legal disclaimer that the installed binary cannot legally be distributed in any form. If this is enabled instead, then the name and logo of the binary will be changed to "Aurora".
