### ISSUE TITLE
WebRTC toggle broken on MacOS ungoogled-chomium

### ISSUE THREAD

**Issue by colvacdir** [Hexavalent-Browser/Hexavalent#126]
Here is the cross reference link to my bug comment.

https://github.com/Eloston/ungoogled-chromium/issues/1725#issuecomment-1099724856

**Comment by loryeam** [comment]
This has already been addressed as of cbcd9ae1541966763fafed60fa28947fc8423e9d. The WebRTC toggle should work fine with the latest set of patches.

**Comment by kramred** [comment]
Yes, I can confirm that the drop-down menu does show up with the changed patches. Thanks!
I'll start a new build with the changed patches on GitHub Actions soon for macOS ungoogled chromium.
