### ISSUE TITLE
Implement non-intrusive SafeBrowsing 

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#13]
We want to have SafeBrowsing as an option where the user can download a database every 30 minutes without having to send site information to Google or any other threat intelligence provider.

**Comment by qua3k** [comment]
Suggest looking at https://github.com/chromium/chromium/blob/master/chrome/browser/safe_browsing/incident_reporting/incident_report_uploader_impl.cc

**Comment by flawedworld** [comment]
It would be nice to explore if having multiple or the ability to choose threat intelligence providers is feasible.

**Comment by qua3k** [comment]
The [Yandex Safe Browsing API](https://yandex.com/dev/safebrowsing/) looks to be a drop in replacement but I've never played with it.

**Comment by flawedworld** [comment]
SafeBrowsing Standard is what we want but we need to ensure that the /fullHashes API is not used which can expose what sites you visit. /threatListUpdates is all we want.
