### ISSUE TITLE
flatpak package

### ISSUE THREAD

**Issue by alexmo1997** [Hexavalent-Browser/Hexavalent#140]
Even though flatpak is not perfect, it significantly increases security, no?

**Comment by flawedworld** [comment]
lol

**Comment by flawedworld** [comment]
I'm not interested in Flatpak due to it lacking the ability to properly run a chromium browser in it.

**Comment by alexmo1997** [comment]
Why's that?
chromium, ungoogled-chromium and even chrome run fine in flatpak.
Is there a security-related aspect flatpak is lacking there?

**Comment by Zanthed** [comment]
Doesn't matter if it "runs fine". It breaks the layer 1 sandbox and replaces it with the significantly weaker flatpak sandbox because flatpak doesn't support nested namespaces.

The maintainers have already made it final that flatpak is not happening.
