### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#25]
Someone that has artistic talent should probably take this otherwise the entire browser is getting it's artwork done in mspaint by me.

**Comment by floshin** [comment]
Not to say that I have a lot of artistic talent, but I made this new colourisation of the chromium logo inspired by the colours of hexavalent chromium, as a suggestion to replace the current one.

![hexavalent-logo](https://user-images.githubusercontent.com/20621752/141651349-44b9bad3-7769-4708-bfdd-b8b25e89b979.png)

**Comment by qua3k** [comment]
I mean it's a fine looking logo but the current one uses the material design and is much flatter. See https://en.wikipedia.org/wiki/File:Chromium_Material_Icon.png for instance.

**Comment by floshin** [comment]
> I mean it's a fine looking logo but the current one uses the material design and is much flatter. See https://en.wikipedia.org/wiki/File:Chromium_Material_Icon.png for instance.

I based this coloration on the very same logo you linked. Only changed colours and a bit of brightness, contrast and saturation. Otherwise, it is the same design. The original also has these "shadows" that you see here and the colour gradient. What would you suggest to change?

**Comment by qua3k** [comment]
> > I mean it's a fine looking logo [...]
> 
> I based this coloration on the very same logo you linked. [...]

It might just be me but it looks more like https://commons.wikimedia.org/wiki/File:Chromium_11_Logo.svg

**Comment by floshin** [comment]
> It might just be me but it looks more like https://commons.wikimedia.org/wiki/File:Chromium_11_Logo.svg, which is the older logo. The current material logo is notably missing these shadows that give it this appearance.

You are right. Sorry, I had confused these two and overlooked those changes at first. Here is a version based on the newer material design logo with my colour suggestion. 

![hexavalent-logo-material](https://user-images.githubusercontent.com/20621752/141660880-7793c157-b81d-436e-b6dc-7468815d4ab8.png)

**Comment by qua3k** [comment]
These look great

**Comment by bob-corporation** [comment]
> otherwise the entire browser is getting it's artwork done in mspaint by me

i would love to see this

**Comment by floshin** [comment]
> These look great

Glad you like it. I have made an icon file (from 256px to 16px) that you can use in the next build if you want.

[hexavalent-icon.zip](https://github.com/Hexavalent-Browser/Hexavalent/files/7533556/hexavalent-icon.zip)

**Comment by floshin** [comment]
Here is an icon based on Chromiums original icon. It is not 100% the same (in smaller) as the hexavalent logo above; but the Chromium icon is also slightly different both in its proportions and colours than their Chromium.svg. So I did the colouration anew instead of just scaling the one above down, in order to stick to the original icon proportions etc.

[hexavalent-icon-2.zip](https://github.com/Hexavalent-Browser/Hexavalent/files/7534838/hexavalent-icon-2.zip)
