### ISSUE TITLE
Replace new tab page

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#28]

**Comment by Seirdy** [comment]
`--disable-ntp-popular-sites` combined with `--disable-features=NtpModules` (the latter is in `chrome://flags`) should do the trick. The latter should prevent loading remote  content.

**Comment by flawedworld** [comment]
nope

**Comment by flawedworld** [comment]
For now I am going to just remove the html content of that page, in future something else can go there.

**Comment by Seirdy** [comment]
Prior art for reference: https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-flag-for-custom-ntp.patch
