### ISSUE TITLE
Add more native search engine options

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#3]

**Comment by flawedworld** [comment]
Example:
https://github.com/bromite/bromite/blob/master/build/patches/Add-DuckDuckGo-Lite-search-engine.patch

**Comment by flawedworld** [comment]
https://github.com/bromite/bromite/blob/master/build/patches/Add-DuckDuckGo-Lite-search-engine.patch

**Comment by Seirdy** [comment]
Mojeek, Gigablast, and Brave Search might be worth considering so users can choose an index besides Google and Bing.

Another "lite" option is Qwant.
