### ISSUE TITLE
Set Client Hints to match Google Chrome

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#32]
Currently it is: ```sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="92"```

We want it to be: ```sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"```

**Comment by Seirdy** [comment]
Would appreciate if this was configurable, but I understand if that'd be too difficult.

**Comment by Seirdy** [comment]
Might also be worth making those hints less unique; on [BrowserLeaks](https://browserleaks.com/client-hints), client hints are shown to reveal the point-release of the Linux kernel; that's way too unique.

In [this screenshot](https://seirdy.one/misc/client-hints.webp), BrowserLeaks labels "low-entropy" hints with an asterisk.

**Comment by flawedworld** [comment]
> Might also be worth making those hints less unique; on [BrowserLeaks](https://browserleaks.com/client-hints), client hints are shown to reveal the point-release of the Linux kernel; that's way too unique.
> 
> In [this screenshot](https://seirdy.one/misc/client-hints.webp), BrowserLeaks labels "low-entropy" hints with an asterisk.

that can be a another issue, i dont really have an interest in doing that though, but i would welcome the change

**Comment by flawedworld** [comment]
https://github.com/GrapheneOS/Vanadium/issues/119

https://github.com/GrapheneOS/Vanadium/pull/123

**Comment by flawedworld** [comment]
> [GrapheneOS/Vanadium#119](https://github.com/GrapheneOS/Vanadium/issues/119)
> 
> [GrapheneOS/Vanadium#123](https://github.com/GrapheneOS/Vanadium/pull/123)

Not applicable to desktop.

**Comment by qua3k** [comment]
Should we close this?
