### ISSUE TITLE
Figure out how to get distribution ready for Windows/macOS

### ISSUE THREAD

**Issue by qua3k** [Hexavalent-Browser/Hexavalent#45]
We need to figure out how to pay for a code signing cert on both Windows and macOS

**Comment by Zanthed** [comment]
Interest in using the macOS App Store was expressed for delivering updates. However, App Store guidelines do not allow non-WebKit browsers, _including the macOS App Store_.

https://developer.apple.com/app-store/review/guidelines/#software-requirements

> 2.5.6 Apps that browse the web must use the appropriate **WebKit** framework and **WebKit** Javascript.

https://developer.apple.com/app-store/review/guidelines/#third-party-software

> 4.7.1 Software offered under this rule must:
> [...]
> only use capabilities available in a standard **WebKit** view (e.g. it must open and run natively in Safari without modifications or additional software); and use **WebKit** and JavaScript Core to run third-party software and should not attempt to extend or expose native platform APIs to third-party software;

Even so, there are other macOS app store restrictions:

> 2.4.5 Apps distributed via the Mac App Store have some additional requirements to keep in mind:
> [...]
> (ii) They must be packaged and submitted **using technologies provided in Xcode**; no third-party installers allowed. They must also be self-contained, single app installation bundles and cannot install code or resources in shared locations.
> [...]
> (vii) They must use the Mac App Store to distribute updates; other update mechanisms are not allowed.
