### ISSUE TITLE
Hexavalent-specific profile path

### ISSUE THREAD

**Issue by Zoraver** [Hexavalent-Browser/Hexavalent#49]
Hexavalent currently uses the default Chromium profile location, which is shared with Chromium packaged by Linux distros and potentially other browsers downstream from Chromium. Hexavalent should have its own profile location.

**Comment by AkechiShiro** [comment]
Hi, anyone knows if this issue is still relevant ? I would like to work on it, hopefully fixing this issue.

**Comment by loryeam** [comment]
@AkechiShiro It is currently being worked on as part of branding (not yet public).
