### ISSUE TITLE
RPM packaging

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#5]

**Comment by Zoraver** [comment]
I looked a bit into Chromium's existing rpm packaging. It appears to have a post-install routine where it installs Google's gpg public key and configures a repository to provide updates. Would these features be worth modifying to install Hexavalent's gpg public key (does one exist?) and repo file, or would it be better to disable these features entirely and put the responsibility on the end user to first set up the repository and then install Hexavalent?

I was also wondering whether changes made to facilitate packaging belong in this repository or in https://github.com/Hexavalent-Browser/scripting? I would image that they belong in the scripting repo, but I wanted to double check.

**Comment by flawedworld** [comment]
For deb and rpm packaging I want to use the existing infrastructure within chromium, patches can just go into the linux folder in the main repo. So we want all the functionality the packages in chromium have.
