### ISSUE TITLE
Enable strict powerful feature restrictions on insecure origins

### ISSUE THREAD

**Issue by Seirdy** [Hexavalent-Browser/Hexavalent#55]
Proposal [on chromium.org](https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).

The toggle seems to be in [`web_preferences.cc`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/common/web_preferences/web_preferences.cc;l=89;drc=861cbcc13edb6281c5d1c7976553840136b1f897) and in `--enable-strict-powerful-feature-restrictions`, which is implied by `--enable-potentially-annoying-security-features`.

**Comment by qua3k** [comment]
Is there anything `enable-strict-powerful-feature-restrictions` does that isn't already restricted by default?

**Comment by Seirdy** [comment]
On Fri, Nov 12, 2021 at 04:13:20PM -0800, qua3k wrote:
>Is there anything that `enable-strict-powerful-feature-restrictions` does that isn't already restricted by default?

After much time spent looking through the source, I've been unable to 
find an answer to this.

However, I do think that it's worth restricting *more* features than 
upstream. Such insecure-origin feature restrictions may include:

- JavaScript
- Remote fonts
- JIT: https://github.com/Hexavalent-Browser/Hexavalent/issues/1
- ...anything else?

If this seems interesting, we could rename this issue.

-- 
/Seirdy
