### ISSUE TITLE
Drop PPAPI

### ISSUE THREAD

**Issue by Seirdy** [Hexavalent-Browser/Hexavalent#63]
Chromium hasn't completely abandoned the legacy PPAPI yet; it will wait till mid-2022. Hexavalent doesn't have to wait that long.

Some components such as the PDF viewer require it. However, there's a disabled-by-default "unseasoned" PDF viewer that doesn't use Pepper, available in `chrome://flags`. It seems to work well on my machine; the only noticeable difference is that the print preview is sometimes a bit slow to load.

**Comment by qua3k** [comment]
There are many components besides Flash and the PDF viewer that need to be migrated off PPAPI; work converting PPAPI messages to Mojo should be submitted upstream, not here.

**Comment by Seirdy** [comment]
On Mon, Nov 22, 2021 at 04:22:37PM -0800, qua3k wrote:
>There are many components besides Flash and the PDF viewer that need to be migrated off PPAPI; work converting PPAPI messages to Mojo should be submitted upstream, not here.

Understood, closing.

-- 
/Seirdy
