### ISSUE TITLE
Do not send x-client-data http header

### ISSUE THREAD

**Issue by Zoraver** [Hexavalent-Browser/Hexavalent#71]
Hexavalent currently sends the `x-client-data` http header in requests to Google-owned domains while not in incognito mode. It is not reset when cookies and site data are cleared, so it adds a relatively persistent fingerprinting surface only exposed to Google. This behavior is described in the [Chrome Privacy Whitepaper](https://www.google.com/chrome/privacy/whitepaper.html#variations). The `x-client-data` header is not sent by Brave, Edge, or Bromite.

Preventing Chromium from sending this header is trivial; I have snippet that accomplishes this with `+1 -4` lines. If this issue is in-scope for Hexavalent, I would be happy to send a pull request.

**Comment by flawedworld** [comment]
@Zoraver can you paste a diff here?

**Comment by Zoraver** [comment]
For Hexavalent 96.0.4664.45:

```diff
diff --git a/components/variations/net/variations_http_headers.cc b/components/variations/net/variations_http_headers.cc
index 8f463333d4b86..510a08db18e0e 100644
--- a/components/variations/net/variations_http_headers.cc
+++ b/components/variations/net/variations_http_headers.cc
@@ -100,10 +100,7 @@ URLValidationResult GetUrlValidationResult(const GURL& url) {
 // Also, logs the result of validating |url| in histograms, one of which ends in
 // |suffix|.
 bool ShouldAppendVariationsHeader(const GURL& url, const std::string& suffix) {
-  URLValidationResult result = GetUrlValidationResult(url);
-  base::UmaHistogramEnumeration(
-      "Variations.Headers.URLValidationResult." + suffix, result);
-  return result == URLValidationResult::kShouldAppend;
+  return false;
 }
 
 // Returns true if the request is sent from a Google web property, i.e. from a
```

After applying this change, I have not observed the `x-client-data` header be sent.

Before applying this change, I also tested the payload of `x-client-data` across three different Hexavalent profiles (two fresh, one previously used). In each of the three profiles, the payload sent was different despite seed-based field trials being disabled.

**Comment by qua3k** [comment]
What if we disable fetching variations?

**Comment by qua3k** [comment]
https://source.chromium.org/chromium/chromium/src/+/main:components/variations/service/variations_service.cc;l=731;drc=94c6fda0960a28d2f7083624c6643ae89cb8d57f

**Comment by qua3k** [comment]
If we do decide to pursue not fetching variations seed it should be done in a way that doesn't break it and cause it to endlessly attempt to fetch the seed.

**Comment by Zoraver** [comment]
Based on my reading of `variations_service.cc` (specifically [`IsFetchingEnabled()`](https://source.chromium.org/chromium/chromium/src/+/main:components/variations/service/variations_service.cc;l=240;drc=b0ca279cada36205f1d4a6e5f730f249ea07a6c0;bpv=1;bpt=1)), it appears to me that variations seed fetching is disabled by default for builds of Chromium that aren't branded as Google Chrome. As a test, I made `DoActualFetch()` a no-op. After I did this, I did not observe any change in behavior across fresh profiles; in each one, the payload of `x-client-data` was different.

After some further experimentation, I found that I was able to make Hexavalent send the same payload for `x-client-data` across fresh profiles by hardcoding `source_value` in [`VariationsIdsProvider::GetAllVariationIds()`](https://source.chromium.org/chromium/chromium/src/+/main:components/variations/variations_ids_provider.cc;l=468;drc=b0ca279cada36205f1d4a6e5f730f249ea07a6c0;bpv=0;bpt=1). If we were to actually implement a change like this, we would probably want to hardcode the low entropy source. Although Hexavalent sent a consistent payload for `x-client-data` in this configuration, the payload it sent greatly differed from the payload sent by Chrome. I believe that this is because Hexavalent is not fetching the variations seed, whereas Chrome is. The `x-client-data` payload looks like one sent by Chromium, not Chrome.

To be clear, I am *not* suggesting that we fetch the variations seed. In my build of Hexavalent, I never observed the `x-client-data` header in a request to a Googled-owned domain from a third-party context, whereas in Chrome, I did. Some variations are sent only in a first-party context, whereas others are sent in all contexts (see <https://source.chromium.org/chromium/chromium/src/+/main:components/variations/variations_associated_data.h;l=53;drc=b0ca279cada36205f1d4a6e5f730f249ea07a6c0;bpv=0;bpt=1>). The variations *currently* used by Chromium appear to only be sent in first-party contexts.

I don't think that there is any perfect solution to this problem. If we just hardcode the low entropy source, we will likely be the only browser that sends client hints that match Chrome alongside an `x-client-data` header that matches Chromium. On the other hand, if we start fetching the variations seed, I believe that we will start to send the `x-client-data` header in third-party contexts, making cross-site tracking easier. I think that the cleanest thing to do would be simply to stop sending the `x-client-data` header; Chrome does this while in incognito mode. I know that it is currently trivial to detect whether the browser is in incognito mode if Javascript is enabled, but this will hopefully become more difficult in the future once the privacy budget is implemented.

**Comment by qua3k** [comment]
Should we take a look at doing this?

**Comment by flawedworld** [comment]
@qua3k We should just stop sending x-client-data completely

**Comment by qua3k** [comment]
> @qua3k We should just stop sending x-client-data completely

Agreed, might use that patch
