### ISSUE TITLE
Increase max declarativenetrequest rule limits

### ISSUE THREAD

**Issue by Seirdy** [Hexavalent-Browser/Hexavalent#75]
Chromium defines some [properties](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#property) that limit the max number of static and dynamic rules(ets) when using DeclarativeNetRequest:

- `MAX_NUMBER_OF_ENABLED_STATIC_RULESETS`
- `MAX_NUMBER_OF_DYNAMIC_AND_SESSION_RULES`
- `MAX_NUMBER_OF_REGEX_RULES`
- `MAX_NUMBER_OF_STATIC_RULESETS`

These values should be user-configurable, or at least increased.

**Comment by flawedworld** [comment]
why

**Comment by Seirdy** [comment]
One thing that hexavalent expressed interest in was replacing addons like uBO with v3's DNR. Increasing these limits will allow more rulesets, and more rules might be necessary given that some advanced uBO rule syntax will need to be broken up into several smaller DNR filters.

**Comment by flawedworld** [comment]
eh sure then but this needs more investigation
