### ISSUE TITLE
Investigate using -fwrapv and/or -ftrapv in the build configuration

### ISSUE THREAD

**Issue by Seirdy** [Hexavalent-Browser/Hexavalent#77]
From https://bugs.chromium.org/p/chromium/issues/detail?id=1166960:

> Integer overflow is undefined behavior for signed integers, which is confusing and can lead to bugs. Let's see what the performance, binary size, and safety impact of these compiler options is.

Hexavalent's priorities lean more sharply towards safety than upstream when balanced against performance and binary size; it might therefore be worth enabling these flags in Hexavalent before upstream.

**Comment by qua3k** [comment]
We're focused on producing a production-quality browser rather than finding/catching bugs, so we won't be using `-ftrapv`.
