### ISSUE TITLE
Implement advertising content blocker using built-in chromium functionality

### ISSUE THREAD

**Issue by flawedworld** [Hexavalent-Browser/Hexavalent#9]

**Comment by flawedworld** [comment]
Bromite has implemented this.

**Comment by Seirdy** [comment]
It doesn't need to worry about network filtering at the global hostname level; that can be taken care of at the DNS level, and I believe Chromium allows specifying custom DNS resolvers. The focus should be cosmetic filtering.

**Comment by JustAnUserLol** [comment]
This will only make Fingerprinting Easier.

**Comment by flawedworld** [comment]
It will be opt in for that reason.

**Comment by Seirdy** [comment]
On Sun, Mar 27, 2022 at 12:33:08AM -0700, JustAnUserLol wrote:
>This will only make Fingerprinting Easier.

Privacy comes in many forms. While content blocking makes identification easier, it can also reduce the amount of data collected about an already-identified user. Different users value different forms of privacy; users concerned about *identification* are better served by the Tor Browser than Hexavalent.

Relevant discussion: https://github.com/privacyguides/privacyguides.org/discussions/662#discussioncomment-2369229

Users are already trivially fingerprintable in most cases. Content blocking serves a different use-case.
